/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_AdditiveOperators(void);
extern void test_MultiplicativeOperators(void);
extern void test_SizeOperator(void);
extern void test_ShiftOperators(void);
extern void test_RelationalOperators(void);
extern void test_BitwiseOperators(void);
extern void test_LogicalOperators(void);
extern void test_SequentialEvaluationOperator(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("TestOperators.c");
  run_test(test_AdditiveOperators, "test_AdditiveOperators", 3);
  run_test(test_MultiplicativeOperators, "test_MultiplicativeOperators", 9);
  run_test(test_SizeOperator, "test_SizeOperator", 16);
  run_test(test_ShiftOperators, "test_ShiftOperators", 27);
  run_test(test_RelationalOperators, "test_RelationalOperators", 39);
  run_test(test_BitwiseOperators, "test_BitwiseOperators", 59);
  run_test(test_LogicalOperators, "test_LogicalOperators", 66);
  run_test(test_SequentialEvaluationOperator, "test_SequentialEvaluationOperator", 75);

  return UNITY_END();
}
